### ISSUE TITLE
Line Numbers Issue🔢

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Geek-Editor-Frontend#136]
By now all of you must have observed that when we enter a new line, a line number gets printed to the left side of the code indicating that the programmer is on the given line number.

You have to change the code for this part:
![image](https://user-images.githubusercontent.com/56023615/136666175-05f1e72f-7148-42f4-ad18-2b2ec18784b7.png)

**Comment by ashutosh3027** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by VineethKumarM** [comment]
Claim

**Comment by Mudit018** [comment]
@Puja-Saraf if you have any doubt regarding this issue, then you can join VC on discord.

**Comment by Mudit018** [comment]
@Puja-Saraf you have time till **10 pm** to complete this issue. After that, it will be **re-assigned**.
