### ISSUE TITLE
Another Design Issues

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Geek-Editor-Frontend#150]
Your next task is to create a design for Dashboard Component in Figma.

## Guidelines
- The page should contain a section or a column for the profile of the programmer. You can refer to online compilers or websites.
- The page should display the rank, saved codes, followers, upvotes of the programmer.

## Minimum Design Criteria (MDC)
Redesign the dashboard component by keeping in view the following points:
- Design should be appropriate i.e. it should look like a dashboard.
- The layout should be clean.

## Note
- The top 3 designs will be selected and will be rewarded with points.
- No extra time will be given for submission after 2 days of posting this issue.
- The final decision will be taken by mentors.
- Figma link should be submitted in the [task2](https://github.com/opencodeiiita/Geek-Editor-Frontend/tree/main/figma-tasks/task2) folder.
- As it is an open to all issue, therefore, no need to claim.

The dashboard component looks like this:
![image](https://user-images.githubusercontent.com/56023615/137352174-7eba741d-bfb6-4233-a118-64bb960cc244.png)
You need to fix it.

**Comment by karankc23** [comment]
Design 🙂

**Comment by karankc23** [comment]
Only top 3 will get the points 🙂
