### ISSUE TITLE
Add .gitignore to tell Git to ignore node_modules and possibliy env files in the future 

### ISSUE THREAD

**Issue by batflarrow** [opencodeiiita/Geek-Editor-Frontend#16]
Currently, the repository does not have a .gitignore file and it is very much required to ignore /node_modules.

**Comment by batflarrow** [comment]
Claim

**Comment by gunwant11** [comment]
claim

**Comment by codesanta142** [comment]
claim

**Comment by hardikarora2** [comment]
claim

**Comment by Mudit018** [comment]
@gunwant11 PR should be send in its issue

**Comment by Mudit018** [comment]
@batflarrow We will review it and then we can assign

**Comment by sauhard22** [comment]
claim

**Comment by batflarrow** [comment]
> @batflarrow We will review it and then we can assign

Yeah okay waiting for the review then..

**Comment by The-Divyansh** [comment]
claim

**Comment by codelord09** [comment]
claim

**Comment by underoot-iota** [comment]
claim

**Comment by Mudit018** [comment]
@batflarrow We have resolved the issue from our side. You can create new issues and tag us

**Comment by batflarrow** [comment]
> @batflarrow We have resolved the issue from our side. You can create new issues and tag us

Ohk cool.
