### ISSUE TITLE
Recreate Dashboard

### ISSUE THREAD

**Issue by Priyal-Saxena** [opencodeiiita/Geek-Editor-Frontend#163]
In this task, you have to implement the below-given design on the dashboard component.

Light Mode - 
![image](https://user-images.githubusercontent.com/76258252/137489958-929f8ad9-d1e8-4ac4-9716-4a6cce7a428b.png)

Dark Mode - 
![image](https://user-images.githubusercontent.com/76258252/137490006-a66ff582-e42e-4bac-b7f6-eaeb78dd8716.png)

figma link - https://www.figma.com/file/RJuCQpR1HVWwBdryIVqYvm/compiler-component?node-id=0%3A1

**Comment by garvitchittora** [comment]
@schandu-eng you already have 3 issues assigned

**Comment by shashwat-mittal** [comment]
Claim

**Comment by KIRTEE-TECH** [comment]
claim

**Comment by aayoushee01** [comment]
claim
