### ISSUE TITLE
logic for compiler (in JS) and setting up the API

### ISSUE THREAD

**Issue by Priyal-Saxena** [opencodeiiita/Geek-Editor-Frontend#179]
Returning from a long time of CSS, now is the time for some JS to take over the project
P.S. We are always open to bugs...XD
so you next task is to write the JS code for compiler. 
# In this task you need to do the following:-
- Analyze what is happening inside the textboxes
- Write a suitable code for accepting the submission, compiling it using the API provided in the readme (link), and displaying - - the compiled output of the code or has the code compiled successfully or not.
- You have to generate your API key and do the needfull.

Note: You can refer to documentation of the API-
- https://ce.judge0.com/
- https://rapidapi.com/judge0-official/api/judge0-ce

**Comment by schandu-eng** [comment]
Claim

**Comment by Ksathwik03** [comment]
claim

**Comment by Mudit018** [comment]
@VineethKumarM assigned
