### ISSUE TITLE
Add Profile Picture

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Frontend#200]
Add a functionality so that a user can upload his/her photo and store it in [Cloudinary](https://cloudinary.com/).
You can use npm module of Cloudinary to store photos online and get a url where the phtos are stored.

Resources
[Cloudinary Docs](https://cloudinary.com/documentation/react_integration)
[Cloudinary NPM](https://www.npmjs.com/package/cloudinary)

**Comment by Ksathwik03** [comment]
Claim

**Comment by Mudit018** [comment]
@Ksathwik03 You already have 3 issues so this one won't be assigned to you
