### ISSUE TITLE
Modifying Readme.md

### ISSUE THREAD

**Issue by ujju20** [opencodeiiita/Geek-Editor-Frontend#53]
I can Beautify Readme.md file like I can add Image Icons of Languages like below one 

<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg" height=80px />

**Comment by ujju20** [comment]
claim

**Comment by Palak-2109** [comment]
claim

**Comment by The-Divyansh** [comment]
claim

**Comment by hardikarora2** [comment]
claim

**Comment by Mudit018** [comment]
But this is not needed in this project. Find suitable issue and then you can ask us
