### ISSUE TITLE
Where is dashboard

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Geek-Editor-Frontend#69]
You might have noticed that the compiler part is there but dashboard Is not, 
   so your next task is to find dashboard and make it visible...XD, you have to create a so called link to dashboard.

**Comment by shlesh** [comment]
claim

**Comment by Mudit018** [comment]
@shlesh assigned

**Comment by Mudit018** [comment]
@shlesh You have to provide a live link of the repo

**Comment by shlesh** [comment]
cool cool

> 
> 
> @shlesh You have to provide a live link of the repo
